name: flame
description: A minimalist Flutter game engine, provides a nice set of somewhat independent modules you can choose from.
version: 1.0.0-rc2-nullsafety.0
homepage: https://github.com/flame-engine/flame

dependencies:
  flutter:
    sdk: flutter
  ordered_set: ^3.0.0-nullsafety.0
  meta: ^1.1.8  # this should probably go after null safety support is in
  vector_math: '>=2.0.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.0-nullsafety

environment:
  sdk: ">=2.12.0-29.10.beta <3.0.0"
  flutter: ">=1.24.0-10.2.pre"

flutter:
  uses-material-design: false
