name: layers
description: Simple project to showcase the layer feature of Flame

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: "layers <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame:
    path: ../../../

  cupertino_icons: ^1.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png
    - assets/images/enemy.png
    - assets/images/player.png
