name: gestures
description: A flame game showcasing the use of gestures callbacks

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame:
      path: ../../../

flutter:
  uses-material-design: false
